<a href="https://colab.research.google.com/github/ednavivianasegura/Plan_de_Formacion_PDI_PAS_2026_privado/blob/main/01_numpy_ejercicios_solv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-title{font-size:20px;font-weight:600;color:#1E3A8A;margin:0 0 .9rem 0;letter-spacing:-.3px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  .nb-body{font-size:14px;color:#1e293b;line-height:1.75;margin-bottom:1rem;}
  .nb-body p{margin:0 0 .6rem;}
  .nb-body-box{font-size:13.5px;color:#1e293b;line-height:1.7;margin-bottom:1rem;padding:10px 14px;background:#F8FAFF;border-left:3px solid #1E3A8A;border-radius:0 6px 6px 0;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  code.ic-g{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#F0FDF4;color:#0F766E;padding:2px 7px;border-radius:4px;border:1px solid #99F6E4;white-space:nowrap;}
  .code-block{background:#0f172a;border-radius:8px;overflow:hidden;margin-top:.5rem;}
  .code-header{display:flex;align-items:center;justify-content:space-between;padding:7px 14px;background:#1e293b;border-bottom:1px solid #334155;}
  .code-lang{font-family:'Source Code Pro',monospace;font-size:11px;color:#64748b;letter-spacing:.5px;text-transform:uppercase;}
  .dots{display:flex;gap:5px;}.dot{width:9px;height:9px;border-radius:50%;}
  .dot-r{background:#ef4444;}.dot-y{background:#f59e0b;}.dot-g{background:#22c55e;}
  pre.cc{padding:14px 18px;font-family:'Source Code Pro',monospace;font-size:13.5px;line-height:1.7;color:#e2e8f0;margin:0;white-space:pre;}
  .kw{color:#7dd3fc;}.mod{color:#a5f3fc;}.al{color:#86efac;}.cm{color:#94A3B8;font-style:italic;}
  .op{color:#f9a8d4;}.num{color:#fcd34d;}.fn{color:#c4b5fd;}.st{color:#86efac;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  /* exercise card */
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);margin-bottom:0;}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
  /* tip */
  .tip{position:relative;display:inline-block;}
  .tip .tt{visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:7px 11px;position:absolute;z-index:999;left:0;top:calc(100%+6px);white-space:normal;max-width:280px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;}
  .tip .tt::before{content:'';position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;}
  .tip:hover .tt{visibility:visible;opacity:1;}
</style>

<div class="nb-cell" style="padding:1.5rem 0 2rem;">

  <div style="display:flex;align-items:flex-start;justify-content:space-between;gap:24px;margin-bottom:1.5rem;padding-bottom:1.25rem;border-bottom:2px solid #1E3A8A;">
    <div style="flex:1;">
      <span style="display:inline-block;font-size:10px;font-weight:600;letter-spacing:1.2px;text-transform:uppercase;color:#0F766E;background:#CCFBF1;border:1px solid #5EEAD4;padding:3px 10px;border-radius:20px;margin-bottom:8px;">Plan de Formación PDI/PAS 2026</span>
      <div style="font-size:11px;color:#475569;letter-spacing:.6px;text-transform:uppercase;margin-bottom:6px;">Formación para la investigación</div>
      <div style="font-size:11px;font-style:italic;color:#475569;margin-bottom:4px;">Módulo 1 — NumPy · Ejercicios</div>
      <h1 style="font-size:24px;font-weight:700;color:#1E3A8A;line-height:1.2;margin:0;">Ejercicios NumPy 1</h1>
    </div>
    <div style="display:flex;flex-direction:column;align-items:center;gap:6px;flex-shrink:0;">
      <img src="https://github.com/ednavivianasegura/AccesoImages/blob/main/logoUR.png?raw=true" alt="Logo Universidad de La Rioja" style="width:72px;height:auto;">
      <div style="font-size:9px;font-weight:600;letter-spacing:.8px;text-transform:uppercase;color:#475569;text-align:center;line-height:1.4;">Universidad<br>de La Rioja</div>
    </div>
  </div>

  <div style="display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-bottom:14px;">
    <div style="background:#fff;border:1px solid rgba(0,0,0,.1);border-radius:10px;padding:1rem;">
      <div style="font-size:10px;font-weight:600;letter-spacing:1px;text-transform:uppercase;color:#475569;margin-bottom:.7rem;padding-bottom:.5rem;border-bottom:1px solid rgba(0,0,0,.07);">
        <i class="ti ti-list-numbers" style="font-size:13px;color:#1E3A8A;vertical-align:-1px;"></i> &nbsp;Ejercicios
      </div>
      <div style="display:flex;flex-direction:column;gap:6px;">
        <div style="font-size:12.5px;color:#1e293b;">16 ejercicios prácticos de NumPy</div>
        <div style="font-size:12.5px;color:#1e293b;">Arrays, matrices, slicing y operaciones</div>
      </div>
    </div>
    <div style="background:#fff;border:1px solid rgba(0,0,0,.1);border-radius:10px;padding:1rem;">
      <div style="font-size:10px;font-weight:600;letter-spacing:1px;text-transform:uppercase;color:#475569;margin-bottom:.7rem;padding-bottom:.5rem;border-bottom:1px solid rgba(0,0,0,.07);">
        <i class="ti ti-target" style="font-size:13px;color:#1E3A8A;vertical-align:-1px;"></i> &nbsp;Objetivo
      </div>
      <div style="font-size:12.5px;color:#1e293b;line-height:1.6;">Consolidar el manejo de <strong style="color:#1E3A8A;">arrays</strong> y <strong style="color:#1E3A8A;">matrices</strong> con NumPy mediante ejercicios progresivos.</div>
    </div>
  </div>

  <div style="display:flex;align-items:center;justify-content:space-between;padding:9px 14px;background:#F8FAFF;border:1px solid #BFDBFE;border-radius:8px;font-size:11px;color:#94A3B8;">
    <span><i class="ti ti-school" style="font-size:12px;color:#1E3A8A;"></i> Universidad de La Rioja — Logroño, La Rioja</span>
    <span><i class="ti ti-calendar" style="font-size:12px;color:#1E3A8A;"></i> Plan de Formación PDI/PAS 2026</span>
  </div>
</div>

In [1]:
import numpy as np

In [2]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-title{font-size:20px;font-weight:600;color:#1E3A8A;margin:0 0 .9rem 0;letter-spacing:-.3px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  .nb-body{font-size:14px;color:#1e293b;line-height:1.75;margin-bottom:1rem;}
  .nb-body p{margin:0 0 .6rem;}
  .nb-body-box{font-size:13.5px;color:#1e293b;line-height:1.7;margin-bottom:1rem;padding:10px 14px;background:#F8FAFF;border-left:3px solid #1E3A8A;border-radius:0 6px 6px 0;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  code.ic-g{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#F0FDF4;color:#0F766E;padding:2px 7px;border-radius:4px;border:1px solid #99F6E4;white-space:nowrap;}
  .code-block{background:#0f172a;border-radius:8px;overflow:hidden;margin-top:.5rem;}
  .code-header{display:flex;align-items:center;justify-content:space-between;padding:7px 14px;background:#1e293b;border-bottom:1px solid #334155;}
  .code-lang{font-family:'Source Code Pro',monospace;font-size:11px;color:#64748b;letter-spacing:.5px;text-transform:uppercase;}
  .dots{display:flex;gap:5px;}.dot{width:9px;height:9px;border-radius:50%;}
  .dot-r{background:#ef4444;}.dot-y{background:#f59e0b;}.dot-g{background:#22c55e;}
  pre.cc{padding:14px 18px;font-family:'Source Code Pro',monospace;font-size:13.5px;line-height:1.7;color:#e2e8f0;margin:0;white-space:pre;}
  .kw{color:#7dd3fc;}.mod{color:#a5f3fc;}.al{color:#86efac;}.cm{color:#94A3B8;font-style:italic;}
  .op{color:#f9a8d4;}.num{color:#fcd34d;}.fn{color:#c4b5fd;}.st{color:#86efac;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  /* exercise card */
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);margin-bottom:0;}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
  /* tip */
  .tip{position:relative;display:inline-block;}
  .tip .tt{visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:7px 11px;position:absolute;z-index:999;left:0;top:calc(100%+6px);white-space:normal;max-width:280px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;}
  .tip .tt::before{content:'';position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;}
  .tip:hover .tt{visibility:visible;opacity:1;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">1</div>
      <div class="ex-title">Vector de números pares</div>
    </div>
    <div class="ex-body">
      <p class="ex-task">▸ Crea un vector con 10 elementos pares.</p>
    </div>
  </div>
 </div>

In [3]:
print("Opción 1: list comprehension + np.array")
vector = np.array([i for i in range(0, 20, 2) if i % 2 == 0])
print(vector)
print("Opción 2: arange con step 2")
v1 = np.arange(0, 20, 2)
print(v1)

Opción 1: list comprehension + np.array
[ 0  2  4  6  8 10 12 14 16 18]
Opción 2: arange con step 2
[ 0  2  4  6  8 10 12 14 16 18]


In [4]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-title{font-size:20px;font-weight:600;color:#1E3A8A;margin:0 0 .9rem 0;letter-spacing:-.3px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  .nb-body{font-size:14px;color:#1e293b;line-height:1.75;margin-bottom:1rem;}
  .nb-body p{margin:0 0 .6rem;}
  .nb-body-box{font-size:13.5px;color:#1e293b;line-height:1.7;margin-bottom:1rem;padding:10px 14px;background:#F8FAFF;border-left:3px solid #1E3A8A;border-radius:0 6px 6px 0;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  code.ic-g{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#F0FDF4;color:#0F766E;padding:2px 7px;border-radius:4px;border:1px solid #99F6E4;white-space:nowrap;}
  .code-block{background:#0f172a;border-radius:8px;overflow:hidden;margin-top:.5rem;}
  .code-header{display:flex;align-items:center;justify-content:space-between;padding:7px 14px;background:#1e293b;border-bottom:1px solid #334155;}
  .code-lang{font-family:'Source Code Pro',monospace;font-size:11px;color:#64748b;letter-spacing:.5px;text-transform:uppercase;}
  .dots{display:flex;gap:5px;}.dot{width:9px;height:9px;border-radius:50%;}
  .dot-r{background:#ef4444;}.dot-y{background:#f59e0b;}.dot-g{background:#22c55e;}
  pre.cc{padding:14px 18px;font-family:'Source Code Pro',monospace;font-size:13.5px;line-height:1.7;color:#e2e8f0;margin:0;white-space:pre;}
  .kw{color:#7dd3fc;}.mod{color:#a5f3fc;}.al{color:#86efac;}.cm{color:#94A3B8;font-style:italic;}
  .op{color:#f9a8d4;}.num{color:#fcd34d;}.fn{color:#c4b5fd;}.st{color:#86efac;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  /* exercise card */
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);margin-bottom:0;}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
  /* tip */
  .tip{position:relative;display:inline-block;}
  .tip .tt{visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:7px 11px;position:absolute;z-index:999;left:0;top:calc(100%+6px);white-space:normal;max-width:280px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;}
  .tip .tt::before{content:'';position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;}
  .tip:hover .tt{visibility:visible;opacity:1;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">2</div>
      <div class="ex-title">Dimensiones y tamaño</div>
    </div>
    <div class="ex-body">
      <p class="ex-task">▸ Obtén el número de dimensiones y el tamaño del vector del ejercicio 1.</p>
    </div>
  </div>
  <div class="nb-note"><i class="ti ti-info-circle" style="color:#0F766E;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="nb-note-text"><code class='ic'>.ndim</code> devuelve el número de ejes (1 para un vector), <code class='ic'>.size</code> el total de elementos y <code class='ic'>.shape</code> la tupla de dimensiones.</span></div>
</div>

In [5]:
vector.ndim

1

In [6]:
vector.size

10

In [7]:
vector.shape

(10,)

In [ ]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-title{font-size:20px;font-weight:600;color:#1E3A8A;margin:0 0 .9rem 0;letter-spacing:-.3px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  .nb-body{font-size:14px;color:#1e293b;line-height:1.75;margin-bottom:1rem;}
  .nb-body p{margin:0 0 .6rem;}
  .nb-body-box{font-size:13.5px;color:#1e293b;line-height:1.7;margin-bottom:1rem;padding:10px 14px;background:#F8FAFF;border-left:3px solid #1E3A8A;border-radius:0 6px 6px 0;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  code.ic-g{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#F0FDF4;color:#0F766E;padding:2px 7px;border-radius:4px;border:1px solid #99F6E4;white-space:nowrap;}
  .code-block{background:#0f172a;border-radius:8px;overflow:hidden;margin-top:.5rem;}
  .code-header{display:flex;align-items:center;justify-content:space-between;padding:7px 14px;background:#1e293b;border-bottom:1px solid #334155;}
  .code-lang{font-family:'Source Code Pro',monospace;font-size:11px;color:#64748b;letter-spacing:.5px;text-transform:uppercase;}
  .dots{display:flex;gap:5px;}.dot{width:9px;height:9px;border-radius:50%;}
  .dot-r{background:#ef4444;}.dot-y{background:#f59e0b;}.dot-g{background:#22c55e;}
  pre.cc{padding:14px 18px;font-family:'Source Code Pro',monospace;font-size:13.5px;line-height:1.7;color:#e2e8f0;margin:0;white-space:pre;}
  .kw{color:#7dd3fc;}.mod{color:#a5f3fc;}.al{color:#86efac;}.cm{color:#94A3B8;font-style:italic;}
  .op{color:#f9a8d4;}.num{color:#fcd34d;}.fn{color:#c4b5fd;}.st{color:#86efac;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  /* exercise card */
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);margin-bottom:0;}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
  /* tip */
  .tip{position:relative;display:inline-block;}
  .tip .tt{visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:7px 11px;position:absolute;z-index:999;left:0;top:calc(100%+6px);white-space:normal;max-width:280px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;}
  .tip .tt::before{content:'';position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;}
  .tip:hover .tt{visibility:visible;opacity:1;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">3</div>
      <div class="ex-title">Matriz de pares e impares</div>
    </div>
    <div class="ex-body">
      <p class="ex-task">▸ Crea una lista con 5 números pares y otra con 5 números impares usando <code class='ic'>list comprehension</code>.</p><p class="ex-task">→ Conviértelas en una matriz de dimensión (5, 2).</p>
    </div>
  </div>
  </div>

In [8]:
pares = np.array([i for i in range(10) if i % 2 == 0])
impares = np.array([i for i in range(10) if i % 2 != 0])

matriz = np.concatenate((pares, impares)).reshape(5, 2)

matriz

array([[0, 2],
       [4, 6],
       [8, 1],
       [3, 5],
       [7, 9]])

In [ ]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-title{font-size:20px;font-weight:600;color:#1E3A8A;margin:0 0 .9rem 0;letter-spacing:-.3px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  .nb-body{font-size:14px;color:#1e293b;line-height:1.75;margin-bottom:1rem;}
  .nb-body p{margin:0 0 .6rem;}
  .nb-body-box{font-size:13.5px;color:#1e293b;line-height:1.7;margin-bottom:1rem;padding:10px 14px;background:#F8FAFF;border-left:3px solid #1E3A8A;border-radius:0 6px 6px 0;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  code.ic-g{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#F0FDF4;color:#0F766E;padding:2px 7px;border-radius:4px;border:1px solid #99F6E4;white-space:nowrap;}
  .code-block{background:#0f172a;border-radius:8px;overflow:hidden;margin-top:.5rem;}
  .code-header{display:flex;align-items:center;justify-content:space-between;padding:7px 14px;background:#1e293b;border-bottom:1px solid #334155;}
  .code-lang{font-family:'Source Code Pro',monospace;font-size:11px;color:#64748b;letter-spacing:.5px;text-transform:uppercase;}
  .dots{display:flex;gap:5px;}.dot{width:9px;height:9px;border-radius:50%;}
  .dot-r{background:#ef4444;}.dot-y{background:#f59e0b;}.dot-g{background:#22c55e;}
  pre.cc{padding:14px 18px;font-family:'Source Code Pro',monospace;font-size:13.5px;line-height:1.7;color:#e2e8f0;margin:0;white-space:pre;}
  .kw{color:#7dd3fc;}.mod{color:#a5f3fc;}.al{color:#86efac;}.cm{color:#94A3B8;font-style:italic;}
  .op{color:#f9a8d4;}.num{color:#fcd34d;}.fn{color:#c4b5fd;}.st{color:#86efac;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  /* exercise card */
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);margin-bottom:0;}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
  /* tip */
  .tip{position:relative;display:inline-block;}
  .tip .tt{visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:7px 11px;position:absolute;z-index:999;left:0;top:calc(100%+6px);white-space:normal;max-width:280px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;}
  .tip .tt::before{content:'';position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;}
  .tip:hover .tt{visibility:visible;opacity:1;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">4</div>
      <div class="ex-title">Tipo de datos</div>
    </div>
    <div class="ex-body">
      <p class="ex-task">▸ Obtén el tipo de datos de la matriz del ejercicio 3.</p>
    </div>
  </div>
  </div>

In [9]:
type(matriz)

numpy.ndarray

In [10]:
matriz.dtype

dtype('int64')

In [ ]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-title{font-size:20px;font-weight:600;color:#1E3A8A;margin:0 0 .9rem 0;letter-spacing:-.3px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  .nb-body{font-size:14px;color:#1e293b;line-height:1.75;margin-bottom:1rem;}
  .nb-body p{margin:0 0 .6rem;}
  .nb-body-box{font-size:13.5px;color:#1e293b;line-height:1.7;margin-bottom:1rem;padding:10px 14px;background:#F8FAFF;border-left:3px solid #1E3A8A;border-radius:0 6px 6px 0;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  code.ic-g{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#F0FDF4;color:#0F766E;padding:2px 7px;border-radius:4px;border:1px solid #99F6E4;white-space:nowrap;}
  .code-block{background:#0f172a;border-radius:8px;overflow:hidden;margin-top:.5rem;}
  .code-header{display:flex;align-items:center;justify-content:space-between;padding:7px 14px;background:#1e293b;border-bottom:1px solid #334155;}
  .code-lang{font-family:'Source Code Pro',monospace;font-size:11px;color:#64748b;letter-spacing:.5px;text-transform:uppercase;}
  .dots{display:flex;gap:5px;}.dot{width:9px;height:9px;border-radius:50%;}
  .dot-r{background:#ef4444;}.dot-y{background:#f59e0b;}.dot-g{background:#22c55e;}
  pre.cc{padding:14px 18px;font-family:'Source Code Pro',monospace;font-size:13.5px;line-height:1.7;color:#e2e8f0;margin:0;white-space:pre;}
  .kw{color:#7dd3fc;}.mod{color:#a5f3fc;}.al{color:#86efac;}.cm{color:#94A3B8;font-style:italic;}
  .op{color:#f9a8d4;}.num{color:#fcd34d;}.fn{color:#c4b5fd;}.st{color:#86efac;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  /* exercise card */
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);margin-bottom:0;}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
  /* tip */
  .tip{position:relative;display:inline-block;}
  .tip .tt{visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:7px 11px;position:absolute;z-index:999;left:0;top:calc(100%+6px);white-space:normal;max-width:280px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;}
  .tip .tt::before{content:'';position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;}
  .tip:hover .tt{visibility:visible;opacity:1;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">5</div>
      <div class="ex-title">Matriz diagonal</div>
    </div>
    <div class="ex-body">
      <p class="ex-task">▸ Crea una matriz de ceros de dimensión (4, 4) y reemplaza los elementos de la diagonal principal por 5.</p>
    </div>
  </div>
  </div>

In [11]:
zeros = np.zeros((4, 4))

zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
zeros + np.identity(4) * 5

array([[5., 0., 0., 0.],
       [0., 5., 0., 0.],
       [0., 0., 5., 0.],
       [0., 0., 0., 5.]])

In [13]:
for i in range(4):
    for j in range(4):
        if i == j:
            zeros[i, j] = 5

zeros

array([[5., 0., 0., 0.],
       [0., 5., 0., 0.],
       [0., 0., 5., 0.],
       [0., 0., 0., 5.]])

In [ ]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-title{font-size:20px;font-weight:600;color:#1E3A8A;margin:0 0 .9rem 0;letter-spacing:-.3px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  .nb-body{font-size:14px;color:#1e293b;line-height:1.75;margin-bottom:1rem;}
  .nb-body p{margin:0 0 .6rem;}
  .nb-body-box{font-size:13.5px;color:#1e293b;line-height:1.7;margin-bottom:1rem;padding:10px 14px;background:#F8FAFF;border-left:3px solid #1E3A8A;border-radius:0 6px 6px 0;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  code.ic-g{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#F0FDF4;color:#0F766E;padding:2px 7px;border-radius:4px;border:1px solid #99F6E4;white-space:nowrap;}
  .code-block{background:#0f172a;border-radius:8px;overflow:hidden;margin-top:.5rem;}
  .code-header{display:flex;align-items:center;justify-content:space-between;padding:7px 14px;background:#1e293b;border-bottom:1px solid #334155;}
  .code-lang{font-family:'Source Code Pro',monospace;font-size:11px;color:#64748b;letter-spacing:.5px;text-transform:uppercase;}
  .dots{display:flex;gap:5px;}.dot{width:9px;height:9px;border-radius:50%;}
  .dot-r{background:#ef4444;}.dot-y{background:#f59e0b;}.dot-g{background:#22c55e;}
  pre.cc{padding:14px 18px;font-family:'Source Code Pro',monospace;font-size:13.5px;line-height:1.7;color:#e2e8f0;margin:0;white-space:pre;}
  .kw{color:#7dd3fc;}.mod{color:#a5f3fc;}.al{color:#86efac;}.cm{color:#94A3B8;font-style:italic;}
  .op{color:#f9a8d4;}.num{color:#fcd34d;}.fn{color:#c4b5fd;}.st{color:#86efac;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  /* exercise card */
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);margin-bottom:0;}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
  /* tip */
  .tip{position:relative;display:inline-block;}
  .tip .tt{visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:7px 11px;position:absolute;z-index:999;left:0;top:calc(100%+6px);white-space:normal;max-width:280px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;}
  .tip .tt::before{content:'';position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;}
  .tip:hover .tt{visibility:visible;opacity:1;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">6</div>
      <div class="ex-title">linspace entre -5 y 5</div>
    </div>
    <div class="ex-body">
      <p class="ex-task">▸ Usa <code class='ic'>np.linspace()</code> para crear un vector con 10 elementos entre -5 y 5.</p>
    </div>
  </div>
  <div class="nb-note"><i class="ti ti-info-circle" style="color:#0F766E;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="nb-note-text"><code class='ic'>np.linspace(a, b, n)</code> incluye <em>ambos extremos</em>. El paso resultante es <code class='ic'>(b-a)/(n-1)</code>. Para -5 a 5 con 10 puntos: paso = 10/9 ≈ 1.111.</span></div>
</div>

In [14]:
np.linspace(-5, 5, 10)

array([-5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
        0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ])

In [ ]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-title{font-size:20px;font-weight:600;color:#1E3A8A;margin:0 0 .9rem 0;letter-spacing:-.3px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  .nb-body{font-size:14px;color:#1e293b;line-height:1.75;margin-bottom:1rem;}
  .nb-body p{margin:0 0 .6rem;}
  .nb-body-box{font-size:13.5px;color:#1e293b;line-height:1.7;margin-bottom:1rem;padding:10px 14px;background:#F8FAFF;border-left:3px solid #1E3A8A;border-radius:0 6px 6px 0;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  code.ic-g{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#F0FDF4;color:#0F766E;padding:2px 7px;border-radius:4px;border:1px solid #99F6E4;white-space:nowrap;}
  .code-block{background:#0f172a;border-radius:8px;overflow:hidden;margin-top:.5rem;}
  .code-header{display:flex;align-items:center;justify-content:space-between;padding:7px 14px;background:#1e293b;border-bottom:1px solid #334155;}
  .code-lang{font-family:'Source Code Pro',monospace;font-size:11px;color:#64748b;letter-spacing:.5px;text-transform:uppercase;}
  .dots{display:flex;gap:5px;}.dot{width:9px;height:9px;border-radius:50%;}
  .dot-r{background:#ef4444;}.dot-y{background:#f59e0b;}.dot-g{background:#22c55e;}
  pre.cc{padding:14px 18px;font-family:'Source Code Pro',monospace;font-size:13.5px;line-height:1.7;color:#e2e8f0;margin:0;white-space:pre;}
  .kw{color:#7dd3fc;}.mod{color:#a5f3fc;}.al{color:#86efac;}.cm{color:#94A3B8;font-style:italic;}
  .op{color:#f9a8d4;}.num{color:#fcd34d;}.fn{color:#c4b5fd;}.st{color:#86efac;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  /* exercise card */
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);margin-bottom:0;}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
  /* tip */
  .tip{position:relative;display:inline-block;}
  .tip .tt{visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:7px 11px;position:absolute;z-index:999;left:0;top:calc(100%+6px);white-space:normal;max-width:280px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;}
  .tip .tt::before{content:'';position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;}
  .tip:hover .tt{visibility:visible;opacity:1;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">7</div>
      <div class="ex-title">Matriz vacía flotante</div>
    </div>
    <div class="ex-body">
      <p class="ex-task">▸ Crea una matriz vacía de tamaño (3, 6) con elementos de tipo flotante.</p>
    </div>
  </div>
  <div class="nb-note"><i class="ti ti-info-circle" style="color:#0F766E;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="nb-note-text"><code class='ic'>np.empty()</code> reserva memoria sin inicializarla — los valores mostrados son residuos de la RAM. Es la función de inicialización más rápida.</span></div>
</div>

In [15]:
empty = np.empty((3, 6), dtype = "float")

empty

array([[4.66408596e-315, 0.00000000e+000, 5.76405441e-317,
        0.00000000e+000, 2.13780573e+161, 1.24002379e+180],
       [4.91223862e+026, 5.98178851e-154, 2.59413295e-085,
        5.77588689e+180, 2.19993033e-152, 2.58436031e+185],
       [6.01346953e-154, 2.16638373e-027, 6.01347002e-154,
        3.32231054e+257, 1.02189775e-152, 1.05879817e-153]])

In [ ]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-title{font-size:20px;font-weight:600;color:#1E3A8A;margin:0 0 .9rem 0;letter-spacing:-.3px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  .nb-body{font-size:14px;color:#1e293b;line-height:1.75;margin-bottom:1rem;}
  .nb-body p{margin:0 0 .6rem;}
  .nb-body-box{font-size:13.5px;color:#1e293b;line-height:1.7;margin-bottom:1rem;padding:10px 14px;background:#F8FAFF;border-left:3px solid #1E3A8A;border-radius:0 6px 6px 0;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  code.ic-g{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#F0FDF4;color:#0F766E;padding:2px 7px;border-radius:4px;border:1px solid #99F6E4;white-space:nowrap;}
  .code-block{background:#0f172a;border-radius:8px;overflow:hidden;margin-top:.5rem;}
  .code-header{display:flex;align-items:center;justify-content:space-between;padding:7px 14px;background:#1e293b;border-bottom:1px solid #334155;}
  .code-lang{font-family:'Source Code Pro',monospace;font-size:11px;color:#64748b;letter-spacing:.5px;text-transform:uppercase;}
  .dots{display:flex;gap:5px;}.dot{width:9px;height:9px;border-radius:50%;}
  .dot-r{background:#ef4444;}.dot-y{background:#f59e0b;}.dot-g{background:#22c55e;}
  pre.cc{padding:14px 18px;font-family:'Source Code Pro',monospace;font-size:13.5px;line-height:1.7;color:#e2e8f0;margin:0;white-space:pre;}
  .kw{color:#7dd3fc;}.mod{color:#a5f3fc;}.al{color:#86efac;}.cm{color:#94A3B8;font-style:italic;}
  .op{color:#f9a8d4;}.num{color:#fcd34d;}.fn{color:#c4b5fd;}.st{color:#86efac;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  /* exercise card */
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);margin-bottom:0;}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
  /* tip */
  .tip{position:relative;display:inline-block;}
  .tip .tt{visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:7px 11px;position:absolute;z-index:999;left:0;top:calc(100%+6px);white-space:normal;max-width:280px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;}
  .tip .tt::before{content:'';position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;}
  .tip:hover .tt{visibility:visible;opacity:1;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">8</div>
      <div class="ex-title">Llenar con números primos</div>
    </div>
    <div class="ex-body">
      <p class="ex-task">▸ Usa la matriz vacía del ejercicio 7 (3×6 = 18 elementos) y rellénala con los primeros 18 números primos.</p><p class="ex-task">→ Investiga e implementa una función que genere números primos.</p>
    </div>
  </div>
  </div>

In [16]:
# Numero primos

primos = [2]

for x in range(3, 100, 2):
    for i in range(2, x):
        if x % i == 0:
            break
    else:
        primos.append(x)


primos = primos[:18]
primos

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61]

In [17]:
# Llenar matriz

p = 0

for i in range(empty.shape[0]):

    for j in range(empty.shape[1]):

        empty[i, j] = primos[p]

        p += 1

empty

array([[ 2.,  3.,  5.,  7., 11., 13.],
       [17., 19., 23., 29., 31., 37.],
       [41., 43., 47., 53., 59., 61.]])

In [ ]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-title{font-size:20px;font-weight:600;color:#1E3A8A;margin:0 0 .9rem 0;letter-spacing:-.3px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  .nb-body{font-size:14px;color:#1e293b;line-height:1.75;margin-bottom:1rem;}
  .nb-body p{margin:0 0 .6rem;}
  .nb-body-box{font-size:13.5px;color:#1e293b;line-height:1.7;margin-bottom:1rem;padding:10px 14px;background:#F8FAFF;border-left:3px solid #1E3A8A;border-radius:0 6px 6px 0;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  code.ic-g{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#F0FDF4;color:#0F766E;padding:2px 7px;border-radius:4px;border:1px solid #99F6E4;white-space:nowrap;}
  .code-block{background:#0f172a;border-radius:8px;overflow:hidden;margin-top:.5rem;}
  .code-header{display:flex;align-items:center;justify-content:space-between;padding:7px 14px;background:#1e293b;border-bottom:1px solid #334155;}
  .code-lang{font-family:'Source Code Pro',monospace;font-size:11px;color:#64748b;letter-spacing:.5px;text-transform:uppercase;}
  .dots{display:flex;gap:5px;}.dot{width:9px;height:9px;border-radius:50%;}
  .dot-r{background:#ef4444;}.dot-y{background:#f59e0b;}.dot-g{background:#22c55e;}
  pre.cc{padding:14px 18px;font-family:'Source Code Pro',monospace;font-size:13.5px;line-height:1.7;color:#e2e8f0;margin:0;white-space:pre;}
  .kw{color:#7dd3fc;}.mod{color:#a5f3fc;}.al{color:#86efac;}.cm{color:#94A3B8;font-style:italic;}
  .op{color:#f9a8d4;}.num{color:#fcd34d;}.fn{color:#c4b5fd;}.st{color:#86efac;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  /* exercise card */
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);margin-bottom:0;}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
  /* tip */
  .tip{position:relative;display:inline-block;}
  .tip .tt{visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:7px 11px;position:absolute;z-index:999;left:0;top:calc(100%+6px);white-space:normal;max-width:280px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;}
  .tip .tt::before{content:'';position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;}
  .tip:hover .tt{visibility:visible;opacity:1;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">9</div>
      <div class="ex-title">Slicing con imagen de referencia</div>
    </div>
    <div class="ex-body">
      <p class="ex-task">▸ Usando la matriz definida abajo, reemplaza los números dentro del círculo por 99 usando slicing.</p><p class="ex-task">→ La imagen de referencia muestra qué elementos deben modificarse.</p>
    </div>
  </div>
 </div>



<style>
  @import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@300;400&display=swap');
  .mat-wrap { padding: 1rem 0; display: inline-block; font-family: 'DM Sans', sans-serif; }
</style>

<div class="mat-wrap">
  <svg id="svg-wrap" xmlns="http://www.w3.org/2000/svg"></svg>
</div>

<script>
  const circled = new Set([3, 6, 8, 9, 15]);
  const cols = 4, rows = 4;
  const cellW = 58, cellH = 58, gapX = 6, gapY = 10;
  const padX = 20, padY = 16;
  const bW = 10, bT = 3;

  const totalW = cols * cellW + (cols - 1) * gapX + 2 * padX + 2 * bW + 8;
  const totalH = rows * cellH + (rows - 1) * gapY + 2 * padY;

  const svg = document.getElementById('svg-wrap');
  svg.setAttribute('width', totalW);
  svg.setAttribute('height', totalH);
  svg.setAttribute('viewBox', `0 0 ${totalW} ${totalH}`);

  function bracket(x, flip) {
    const x1 = flip ? x : x + bW;
    const x2 = flip ? x + bW : x;
    return `M ${x1} ${padY} L ${x2} ${padY} L ${x2} ${totalH - padY} L ${x1} ${totalH - padY}`;
  }

  ['left','right'].forEach((side, idx) => {
    const x = idx === 0 ? 4 : totalW - 4 - bW;
    const p = document.createElementNS('http://www.w3.org/2000/svg','path');
    p.setAttribute('d', bracket(x, idx === 1));
    p.setAttribute('fill', 'none');
    p.setAttribute('stroke', '#1e293b');
    p.setAttribute('stroke-width', bT);
    p.setAttribute('stroke-linecap', 'round');
    p.setAttribute('stroke-linejoin', 'round');
    svg.appendChild(p);
  });

  for (let i = 1; i <= 16; i++) {
    const row = Math.floor((i - 1) / cols);
    const col = (i - 1) % cols;
    const cx = bW + 8 + padX + col * (cellW + gapX) + cellW / 2;
    const cy = padY + row * (cellH + gapY) + cellH / 2;
    const isCircled = circled.has(i);

    if (isCircled) {
      const c = document.createElementNS('http://www.w3.org/2000/svg','circle');
      c.setAttribute('cx', cx);
      c.setAttribute('cy', cy);
      c.setAttribute('r', cellH / 2 - 2);
      c.setAttribute('fill', 'none');
      c.setAttribute('stroke', '#185FA5');
      c.setAttribute('stroke-width', '2.5');
      svg.appendChild(c);
    }

    const t = document.createElementNS('http://www.w3.org/2000/svg','text');
    t.setAttribute('x', cx);
    t.setAttribute('y', cy + 7);
    t.setAttribute('text-anchor', 'middle');
    t.setAttribute('font-size', '22');
    t.setAttribute('font-weight', '400');
    t.setAttribute('font-family', 'DM Sans, sans-serif');
    t.setAttribute('fill', isCircled ? '#185FA5' : '#1e293b');
    t.textContent = i;
    svg.appendChild(t);
  }
</script>

In [18]:
matriz = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])

In [19]:
matriz[0, 2] = 99
matriz[1, 1] = 99
matriz[1, -1] = 99
matriz[-2, 0] = 99
matriz[-1, -2] = 99

In [20]:
matriz

array([[ 1,  2, 99,  4],
       [ 5, 99,  7, 99],
       [99, 10, 11, 12],
       [13, 14, 99, 16]])

In [ ]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-title{font-size:20px;font-weight:600;color:#1E3A8A;margin:0 0 .9rem 0;letter-spacing:-.3px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  .nb-body{font-size:14px;color:#1e293b;line-height:1.75;margin-bottom:1rem;}
  .nb-body p{margin:0 0 .6rem;}
  .nb-body-box{font-size:13.5px;color:#1e293b;line-height:1.7;margin-bottom:1rem;padding:10px 14px;background:#F8FAFF;border-left:3px solid #1E3A8A;border-radius:0 6px 6px 0;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  code.ic-g{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#F0FDF4;color:#0F766E;padding:2px 7px;border-radius:4px;border:1px solid #99F6E4;white-space:nowrap;}
  .code-block{background:#0f172a;border-radius:8px;overflow:hidden;margin-top:.5rem;}
  .code-header{display:flex;align-items:center;justify-content:space-between;padding:7px 14px;background:#1e293b;border-bottom:1px solid #334155;}
  .code-lang{font-family:'Source Code Pro',monospace;font-size:11px;color:#64748b;letter-spacing:.5px;text-transform:uppercase;}
  .dots{display:flex;gap:5px;}.dot{width:9px;height:9px;border-radius:50%;}
  .dot-r{background:#ef4444;}.dot-y{background:#f59e0b;}.dot-g{background:#22c55e;}
  pre.cc{padding:14px 18px;font-family:'Source Code Pro',monospace;font-size:13.5px;line-height:1.7;color:#e2e8f0;margin:0;white-space:pre;}
  .kw{color:#7dd3fc;}.mod{color:#a5f3fc;}.al{color:#86efac;}.cm{color:#94A3B8;font-style:italic;}
  .op{color:#f9a8d4;}.num{color:#fcd34d;}.fn{color:#c4b5fd;}.st{color:#86efac;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  /* exercise card */
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);margin-bottom:0;}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
  /* tip */
  .tip{position:relative;display:inline-block;}
  .tip .tt{visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:7px 11px;position:absolute;z-index:999;left:0;top:calc(100%+6px);white-space:normal;max-width:280px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;}
  .tip .tt::before{content:'';position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;}
  .tip:hover .tt{visibility:visible;opacity:1;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">10</div>
      <div class="ex-title">Primera y tercera fila</div>
    </div>
    <div class="ex-body">
      <p class="ex-task">▸ Obtén la primera y tercera fila de la matriz del ejercicio 9.</p>
    </div>
  </div>
 </div>

In [21]:
matriz[[0, 2], :]

array([[ 1,  2, 99,  4],
       [99, 10, 11, 12]])

In [22]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-title{font-size:20px;font-weight:600;color:#1E3A8A;margin:0 0 .9rem 0;letter-spacing:-.3px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  .nb-body{font-size:14px;color:#1e293b;line-height:1.75;margin-bottom:1rem;}
  .nb-body p{margin:0 0 .6rem;}
  .nb-body-box{font-size:13.5px;color:#1e293b;line-height:1.7;margin-bottom:1rem;padding:10px 14px;background:#F8FAFF;border-left:3px solid #1E3A8A;border-radius:0 6px 6px 0;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  code.ic-g{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#F0FDF4;color:#0F766E;padding:2px 7px;border-radius:4px;border:1px solid #99F6E4;white-space:nowrap;}
  .code-block{background:#0f172a;border-radius:8px;overflow:hidden;margin-top:.5rem;}
  .code-header{display:flex;align-items:center;justify-content:space-between;padding:7px 14px;background:#1e293b;border-bottom:1px solid #334155;}
  .code-lang{font-family:'Source Code Pro',monospace;font-size:11px;color:#64748b;letter-spacing:.5px;text-transform:uppercase;}
  .dots{display:flex;gap:5px;}.dot{width:9px;height:9px;border-radius:50%;}
  .dot-r{background:#ef4444;}.dot-y{background:#f59e0b;}.dot-g{background:#22c55e;}
  pre.cc{padding:14px 18px;font-family:'Source Code Pro',monospace;font-size:13.5px;line-height:1.7;color:#e2e8f0;margin:0;white-space:pre;}
  .kw{color:#7dd3fc;}.mod{color:#a5f3fc;}.al{color:#86efac;}.cm{color:#94A3B8;font-style:italic;}
  .op{color:#f9a8d4;}.num{color:#fcd34d;}.fn{color:#c4b5fd;}.st{color:#86efac;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  /* exercise card */
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);margin-bottom:0;}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
  /* tip */
  .tip{position:relative;display:inline-block;}
  .tip .tt{visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:7px 11px;position:absolute;z-index:999;left:0;top:calc(100%+6px);white-space:normal;max-width:280px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;}
  .tip .tt::before{content:'';position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;}
  .tip:hover .tt{visibility:visible;opacity:1;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">11</div>
      <div class="ex-title">Tercera columna</div>
    </div>
    <div class="ex-body">
      <p class="ex-task">▸ Obtén la tercera columna de la matriz.</p>
    </div>
  </div>
  <div class="nb-note"><i class="ti ti-info-circle" style="color:#0F766E;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="nb-note-text">Para seleccionar una columna completa: <code class='ic'>matriz[:, idx]</code>. El <code class='ic'>:</code> en filas significa "todas las filas".</span></div>
</div>

In [23]:
matriz[:, 2]

array([99,  7, 11, 99])

In [ ]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-title{font-size:20px;font-weight:600;color:#1E3A8A;margin:0 0 .9rem 0;letter-spacing:-.3px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  .nb-body{font-size:14px;color:#1e293b;line-height:1.75;margin-bottom:1rem;}
  .nb-body p{margin:0 0 .6rem;}
  .nb-body-box{font-size:13.5px;color:#1e293b;line-height:1.7;margin-bottom:1rem;padding:10px 14px;background:#F8FAFF;border-left:3px solid #1E3A8A;border-radius:0 6px 6px 0;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  code.ic-g{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#F0FDF4;color:#0F766E;padding:2px 7px;border-radius:4px;border:1px solid #99F6E4;white-space:nowrap;}
  .code-block{background:#0f172a;border-radius:8px;overflow:hidden;margin-top:.5rem;}
  .code-header{display:flex;align-items:center;justify-content:space-between;padding:7px 14px;background:#1e293b;border-bottom:1px solid #334155;}
  .code-lang{font-family:'Source Code Pro',monospace;font-size:11px;color:#64748b;letter-spacing:.5px;text-transform:uppercase;}
  .dots{display:flex;gap:5px;}.dot{width:9px;height:9px;border-radius:50%;}
  .dot-r{background:#ef4444;}.dot-y{background:#f59e0b;}.dot-g{background:#22c55e;}
  pre.cc{padding:14px 18px;font-family:'Source Code Pro',monospace;font-size:13.5px;line-height:1.7;color:#e2e8f0;margin:0;white-space:pre;}
  .kw{color:#7dd3fc;}.mod{color:#a5f3fc;}.al{color:#86efac;}.cm{color:#94A3B8;font-style:italic;}
  .op{color:#f9a8d4;}.num{color:#fcd34d;}.fn{color:#c4b5fd;}.st{color:#86efac;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  /* exercise card */
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);margin-bottom:0;}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
  /* tip */
  .tip{position:relative;display:inline-block;}
  .tip .tt{visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:7px 11px;position:absolute;z-index:999;left:0;top:calc(100%+6px);white-space:normal;max-width:280px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;}
  .tip .tt::before{content:'';position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;}
  .tip:hover .tt{visibility:visible;opacity:1;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">12</div>
      <div class="ex-title">Segunda y tercera columna</div>
    </div>
    <div class="ex-body">
      <p class="ex-task">▸ Obtén la segunda y tercera columna de la matriz.</p>
    </div>
  </div>
  </div>

In [24]:
matriz[:, [1, 2]]

array([[ 2, 99],
       [99,  7],
       [10, 11],
       [14, 99]])

In [ ]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-title{font-size:20px;font-weight:600;color:#1E3A8A;margin:0 0 .9rem 0;letter-spacing:-.3px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  .nb-body{font-size:14px;color:#1e293b;line-height:1.75;margin-bottom:1rem;}
  .nb-body p{margin:0 0 .6rem;}
  .nb-body-box{font-size:13.5px;color:#1e293b;line-height:1.7;margin-bottom:1rem;padding:10px 14px;background:#F8FAFF;border-left:3px solid #1E3A8A;border-radius:0 6px 6px 0;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  code.ic-g{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#F0FDF4;color:#0F766E;padding:2px 7px;border-radius:4px;border:1px solid #99F6E4;white-space:nowrap;}
  .code-block{background:#0f172a;border-radius:8px;overflow:hidden;margin-top:.5rem;}
  .code-header{display:flex;align-items:center;justify-content:space-between;padding:7px 14px;background:#1e293b;border-bottom:1px solid #334155;}
  .code-lang{font-family:'Source Code Pro',monospace;font-size:11px;color:#64748b;letter-spacing:.5px;text-transform:uppercase;}
  .dots{display:flex;gap:5px;}.dot{width:9px;height:9px;border-radius:50%;}
  .dot-r{background:#ef4444;}.dot-y{background:#f59e0b;}.dot-g{background:#22c55e;}
  pre.cc{padding:14px 18px;font-family:'Source Code Pro',monospace;font-size:13.5px;line-height:1.7;color:#e2e8f0;margin:0;white-space:pre;}
  .kw{color:#7dd3fc;}.mod{color:#a5f3fc;}.al{color:#86efac;}.cm{color:#94A3B8;font-style:italic;}
  .op{color:#f9a8d4;}.num{color:#fcd34d;}.fn{color:#c4b5fd;}.st{color:#86efac;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  /* exercise card */
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);margin-bottom:0;}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
  /* tip */
  .tip{position:relative;display:inline-block;}
  .tip .tt{visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:7px 11px;position:absolute;z-index:999;left:0;top:calc(100%+6px);white-space:normal;max-width:280px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;}
  .tip .tt::before{content:'';position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;}
  .tip:hover .tt{visibility:visible;opacity:1;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">13</div>
      <div class="ex-title">Submatriz central</div>
    </div>
    <div class="ex-body">
      <p class="ex-task">▸ Obtén una submatriz con los 4 números del centro de la matriz.</p>
    </div>
  </div>
 </div>

In [25]:
matriz[1:-1, 1:-1]

array([[99,  7],
       [10, 11]])

In [ ]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-title{font-size:20px;font-weight:600;color:#1E3A8A;margin:0 0 .9rem 0;letter-spacing:-.3px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  .nb-body{font-size:14px;color:#1e293b;line-height:1.75;margin-bottom:1rem;}
  .nb-body p{margin:0 0 .6rem;}
  .nb-body-box{font-size:13.5px;color:#1e293b;line-height:1.7;margin-bottom:1rem;padding:10px 14px;background:#F8FAFF;border-left:3px solid #1E3A8A;border-radius:0 6px 6px 0;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  code.ic-g{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#F0FDF4;color:#0F766E;padding:2px 7px;border-radius:4px;border:1px solid #99F6E4;white-space:nowrap;}
  .code-block{background:#0f172a;border-radius:8px;overflow:hidden;margin-top:.5rem;}
  .code-header{display:flex;align-items:center;justify-content:space-between;padding:7px 14px;background:#1e293b;border-bottom:1px solid #334155;}
  .code-lang{font-family:'Source Code Pro',monospace;font-size:11px;color:#64748b;letter-spacing:.5px;text-transform:uppercase;}
  .dots{display:flex;gap:5px;}.dot{width:9px;height:9px;border-radius:50%;}
  .dot-r{background:#ef4444;}.dot-y{background:#f59e0b;}.dot-g{background:#22c55e;}
  pre.cc{padding:14px 18px;font-family:'Source Code Pro',monospace;font-size:13.5px;line-height:1.7;color:#e2e8f0;margin:0;white-space:pre;}
  .kw{color:#7dd3fc;}.mod{color:#a5f3fc;}.al{color:#86efac;}.cm{color:#94A3B8;font-style:italic;}
  .op{color:#f9a8d4;}.num{color:#fcd34d;}.fn{color:#c4b5fd;}.st{color:#86efac;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  /* exercise card */
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);margin-bottom:0;}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
  /* tip */
  .tip{position:relative;display:inline-block;}
  .tip .tt{visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:7px 11px;position:absolute;z-index:999;left:0;top:calc(100%+6px);white-space:normal;max-width:280px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;}
  .tip .tt::before{content:'';position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;}
  .tip:hover .tt{visibility:visible;opacity:1;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">14</div>
      <div class="ex-title">flatten</div>
    </div>
    <div class="ex-body">
      <p class="ex-task">▸ Aplica <code class='ic'>.flatten()</code> a la submatriz anterior para obtener un vector.</p>
    </div>
  </div>
  </div>

In [26]:
matriz = matriz.flatten()
matriz

array([ 1,  2, 99,  4,  5, 99,  7, 99, 99, 10, 11, 12, 13, 14, 99, 16])

In [ ]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-title{font-size:20px;font-weight:600;color:#1E3A8A;margin:0 0 .9rem 0;letter-spacing:-.3px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  .nb-body{font-size:14px;color:#1e293b;line-height:1.75;margin-bottom:1rem;}
  .nb-body p{margin:0 0 .6rem;}
  .nb-body-box{font-size:13.5px;color:#1e293b;line-height:1.7;margin-bottom:1rem;padding:10px 14px;background:#F8FAFF;border-left:3px solid #1E3A8A;border-radius:0 6px 6px 0;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  code.ic-g{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#F0FDF4;color:#0F766E;padding:2px 7px;border-radius:4px;border:1px solid #99F6E4;white-space:nowrap;}
  .code-block{background:#0f172a;border-radius:8px;overflow:hidden;margin-top:.5rem;}
  .code-header{display:flex;align-items:center;justify-content:space-between;padding:7px 14px;background:#1e293b;border-bottom:1px solid #334155;}
  .code-lang{font-family:'Source Code Pro',monospace;font-size:11px;color:#64748b;letter-spacing:.5px;text-transform:uppercase;}
  .dots{display:flex;gap:5px;}.dot{width:9px;height:9px;border-radius:50%;}
  .dot-r{background:#ef4444;}.dot-y{background:#f59e0b;}.dot-g{background:#22c55e;}
  pre.cc{padding:14px 18px;font-family:'Source Code Pro',monospace;font-size:13.5px;line-height:1.7;color:#e2e8f0;margin:0;white-space:pre;}
  .kw{color:#7dd3fc;}.mod{color:#a5f3fc;}.al{color:#86efac;}.cm{color:#94A3B8;font-style:italic;}
  .op{color:#f9a8d4;}.num{color:#fcd34d;}.fn{color:#c4b5fd;}.st{color:#86efac;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  /* exercise card */
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);margin-bottom:0;}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
  /* tip */
  .tip{position:relative;display:inline-block;}
  .tip .tt{visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:7px 11px;position:absolute;z-index:999;left:0;top:calc(100%+6px);white-space:normal;max-width:280px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;}
  .tip .tt::before{content:'';position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;}
  .tip:hover .tt{visibility:visible;opacity:1;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">15</div>
      <div class="ex-title">reshape a (1, 4)</div>
    </div>
    <div class="ex-body">
      <p class="ex-task">▸ Aplica <code class='ic'>.reshape()</code> al vector del ejercicio 14 para obtener una matriz de dimensión (1, 4).</p>
    </div>
  </div>
  </div>

In [27]:
matriz = matriz.reshape(2, 8)
matriz

array([[ 1,  2, 99,  4,  5, 99,  7, 99],
       [99, 10, 11, 12, 13, 14, 99, 16]])

In [ ]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-title{font-size:20px;font-weight:600;color:#1E3A8A;margin:0 0 .9rem 0;letter-spacing:-.3px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  .nb-body{font-size:14px;color:#1e293b;line-height:1.75;margin-bottom:1rem;}
  .nb-body p{margin:0 0 .6rem;}
  .nb-body-box{font-size:13.5px;color:#1e293b;line-height:1.7;margin-bottom:1rem;padding:10px 14px;background:#F8FAFF;border-left:3px solid #1E3A8A;border-radius:0 6px 6px 0;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  code.ic-g{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#F0FDF4;color:#0F766E;padding:2px 7px;border-radius:4px;border:1px solid #99F6E4;white-space:nowrap;}
  .code-block{background:#0f172a;border-radius:8px;overflow:hidden;margin-top:.5rem;}
  .code-header{display:flex;align-items:center;justify-content:space-between;padding:7px 14px;background:#1e293b;border-bottom:1px solid #334155;}
  .code-lang{font-family:'Source Code Pro',monospace;font-size:11px;color:#64748b;letter-spacing:.5px;text-transform:uppercase;}
  .dots{display:flex;gap:5px;}.dot{width:9px;height:9px;border-radius:50%;}
  .dot-r{background:#ef4444;}.dot-y{background:#f59e0b;}.dot-g{background:#22c55e;}
  pre.cc{padding:14px 18px;font-family:'Source Code Pro',monospace;font-size:13.5px;line-height:1.7;color:#e2e8f0;margin:0;white-space:pre;}
  .kw{color:#7dd3fc;}.mod{color:#a5f3fc;}.al{color:#86efac;}.cm{color:#94A3B8;font-style:italic;}
  .op{color:#f9a8d4;}.num{color:#fcd34d;}.fn{color:#c4b5fd;}.st{color:#86efac;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  /* exercise card */
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);margin-bottom:0;}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
  /* tip */
  .tip{position:relative;display:inline-block;}
  .tip .tt{visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:7px 11px;position:absolute;z-index:999;left:0;top:calc(100%+6px);white-space:normal;max-width:280px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;}
  .tip .tt::before{content:'';position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;}
  .tip:hover .tt{visibility:visible;opacity:1;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">16</div>
      <div class="ex-title">Concatenación vertical</div>
    </div>
    <div class="ex-body">
      <p class="ex-task">▸ Crea dos matrices de dimensión (4, 4) con números aleatorios.</p><p class="ex-task">→ Concaténalas verticalmente.</p>
    </div>
  </div>
  </div>

In [28]:
A = np.random.randn(4, 4)
B = np.random.randn(4, 4)

np.concatenate((A, B), axis = 0)

array([[ 0.96949915,  1.24397147,  1.44044017,  0.57072526],
       [-1.11757266,  0.65797383, -2.04682783,  0.50518018],
       [ 0.83442652, -0.83644996, -0.15902115, -1.24539718],
       [ 1.25487722, -0.28085707, -0.26413854, -0.08834331],
       [-0.40077612, -0.13795988,  1.28244458,  0.80992549],
       [ 0.8774972 ,  0.87013701,  0.81419178,  0.31676832],
       [-0.45513183,  0.58880698, -0.62716641,  1.2759155 ],
       [-0.01197556, -0.43508748,  1.34769895, -0.53421655]])